version = "1.0"

[main]

  [main.registration]
  name.en = "Registration"

    [main.registration.open_registration]
    ask.en = "Allow new user registrations"
    type = "boolean"
    yes = true
    no = false
    bind = "null"

