#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "atuin"
name = "Atuin"
description.en = "Self-hosted Atuin for syncing and backing up encrypted shell history across devices"

version = "18.10.0~ynh1"

maintainers = ["ximikos"]

[upstream]
license = "MIT"
website = "https://atuin.sh"
admindoc = "https://docs.atuin.sh/cli/self-hosting/server-setup/"
userdoc = "https://docs.atuin.sh/cli/"
code = "https://github.com/atuinsh/atuin"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = ["amd64"]
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "500M"
ram.build = "50M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/atuin"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/atuinsh/atuin/releases/download/v18.10.0/atuin-x86_64-unknown-linux-gnu.tar.gz"
    sha256 = "21fd614adca7bb6e26b7e37d867b7a8ff3436df8821e74de3941bc18533b1898"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "atuin-x86_64-unknown-linux-gnu\\.tar\\.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.show_tile = false

    [resources.ports]
